### ISSUE TITLE
support tasks with long running scripts

### ISSUE THREAD

**Issue by bardiarastin** [jadjoubran/webdash-npm-scripts#7]
Hello, i just installed webdash on one of my projects bootstrapped with create react app and i faced two issues: 
1: running the start task the start button always keeps loading while i want my script to keep running (shows loading indicator)
suggestion as a user: for long running tasks show an ✔icon for status that this is running successfully 
2: when i want to stop the process of watching my files compiling and ... there is no option to do that
suggestion: on click on ✔icon prompt user to stop that process

a problem for these suggestions is that i don't have any idea of how we could realize which scripts are long running tasks i would be happy to send a PR if you have any ideas ❤️

**Comment by jadjoubran** [comment]
Hi @bardiarastin 
Thanks for giving webdash a try and opening an issue 😄 

Indeed long running tasks pose multiple problems, including reloading the page as mentioned in #6 

Afaik, I don't think there's a way to programmatically know that a script is long running but not slow

I have an idea though, we could create a configuration entry in `webdash.json`, something like:
`longRunningScripts`: ['start', 'dev', 'serve']`
so that we can give end users the ability to customize them
and of course, we'll default `webdash.json` to some smart values, such as `'start', 'dev', 'serve'` and other long running tasks that we can find on popular repos

This solves issue `1` that you mentioned, what do yo think?

Regarding issue `2`, you should see a `stop` icon as soon as you hover on the button

<img width="678" alt="screen shot 2018-03-27 at 3 10 17 pm" src="https://user-images.githubusercontent.com/2265232/37966397-02fe5148-31d1-11e8-9c6e-544b2b1b9d7c.png">

is this not working for you?

**Comment by bardiarastin** [comment]
about issue 2 problem is that the app thinks that execution of long running process is not finished yet so it shows the Loading Indicator instead of a stop icon.
but with your solution for issue 1 the problem gets solved cause we know long running tasks so we can show some icon like this is running successfully + option to terminate that process
is it okay that i work on a PR for your solution ?!

**Comment by bardiarastin** [comment]
okay so here is my PR: https://github.com/jadjoubran/webdash-npm-scripts/pull/8 
this adds support for long running processes,
i'm not familiar with polymer so i don't have any idea of how can i implement an event system between server and index html so i can print output of processes to UI, for now there is just console.logs

for #6  i have a solution, instead of keeping the whole processes in a variable just keep pid of them in variables so we can simply write them into a json file and make some caching...

**Comment by jadjoubran** [comment]
> about issue 2 problem is that the app thinks that execution of long running process is not finished yet so it shows the Loading Indicator instead of a stop icon.
That's weird though, once you **hover** on the button it should show you the `stop` icon

It's awesome that you sent a PR, I'll test it locally today and let you know if I have any feedback, thanks 😄 
Regarding the communication between the backend and frontend, its' covered in the [wiki here]
(https://github.com/jadjoubran/webdash/wiki/Create-a-plugin#using-the-back-end)

Yeah makes sense, #6 can be fixed as you suggested (except maybe we can use localstorage?)
Let's finalize this one first before moving to it though
Cheers

**Comment by bardiarastin** [comment]
i've read the wiki and code of webdash-npm-scripts.html but there is no docs for how to subscribe for data, i was thinking about something like streaming console output using https://github.com/socketio/socket.io for example, another solution is using javascript intervals but this way we need to keep console output somewhere in api.js so i guess things get complicated, any ideas ?

**Comment by jadjoubran** [comment]
hmm I wouldn't stream the data back to webdash, keeping them in the console is a good idea for now
you'd use webdash to start the server, but then you could still use the console if something breaks (normally you don't look at the output of serve)

for regular tasks (not long running) you can already see the output at the end in a paper dialog

**Comment by bardiarastin** [comment]
so according to this right now my pull request is working just fine, let me know for reviews then we'll go for #6 😎🍻

**Comment by bardiarastin** [comment]
stoping long processes is still buggy :(, i'll dispatch an update tonight
